[browser]
# Masque la barre latérale pour tous les utilisateurs non-développeurs,
# y compris le bouton 'Edit' (Crayon) et le bouton 'Settings' (Paramètres).
toolbarMode = "minimal"

[server]
# Empêche l'affichage du bouton "Fork/Lien Github" sur la version déployée.
# Cela rend l'application visible SANS possibilité de cloner le code source pour les utilisateurs.
headless = true
enableCORS = true
enableXsrfProtection = true
